TRUNCATE TABLE clientes RESTART IDENTITY;
INSERT INTO clientes (nombre, latitud, longitud, activo, ciudad, tipo_cliente, cadena) VALUES ('bernubbi', -25.3412883, -57.5080709, true, 'Asunción', 'minorista/gastronómico', 'NINGUNO');
INSERT INTO clientes (nombre, latitud, longitud, activo, ciudad, tipo_cliente, cadena) VALUES ('Sara Enciso', -25.3681137, -57.5305474, true, 'Asunción', 'minorista/gastronómico', 'NINGUNO');
INSERT INTO clientes (nombre, latitud, longitud, activo, ciudad, tipo_cliente, cadena) VALUES ('Liz Salinas', -25.2178609, -57.5373326, true, 'Luque', 'minorista/gastronómico', 'NINGUNO');
INSERT INTO clientes (nombre, latitud, longitud, activo, ciudad, tipo_cliente, cadena) VALUES ('Pizzeria Romana 2', -25.2959951, -57.6688104, true, 'Asunción', 'minorista/gastronómico', 'NINGUNO');
INSERT INTO clientes (nombre, latitud, longitud, activo, ciudad, tipo_cliente, cadena) VALUES ('Dulce Compañia', -25.3002066, -57.5803444, true, 'Asunción', 'minorista/gastronómico', 'NINGUNO');
INSERT INTO clientes (nombre, latitud, longitud, activo, ciudad, tipo_cliente, cadena) VALUES ('Productos Edward', -25.3212078, -57.5618762, true, 'Asunción', 'minorista/gastronómico', 'NINGUNO');
INSERT INTO clientes (nombre, latitud, longitud, activo, ciudad, tipo_cliente, cadena) VALUES ('Aristeo', -25.3452226, -57.5121051, true, 'Asunción', 'minorista/gastronómico', 'NINGUNO');
INSERT INTO clientes (nombre, latitud, longitud, activo, ciudad, tipo_cliente, cadena) VALUES ('Estirpe Guarani', -25.2545069, -57.5528793, true, 'Asunción', 'minorista/gastronómico', 'NINGUNO');
INSERT INTO clientes (nombre, latitud, longitud, activo, ciudad, tipo_cliente, cadena) VALUES ('Supermercado La Preferida', -25.2767578, -57.641037, true, 'Asunción', 'supermercado', 'LA PREFERIDA');
INSERT INTO clientes (nombre, latitud, longitud, activo, ciudad, tipo_cliente, cadena) VALUES ('Richar Lopez', -25.3379972, -57.5036685, true, 'Asunción', 'minorista/gastronómico', 'NINGUNO');
INSERT INTO clientes (nombre, latitud, longitud, activo, ciudad, tipo_cliente, cadena) VALUES ('Marcia Regina', -25.3567692, -57.4817189, true, 'San Lorenzo', 'minorista/gastronómico', 'NINGUNO');
INSERT INTO clientes (nombre, latitud, longitud, activo, ciudad, tipo_cliente, cadena) VALUES ('Zonia Montserrat', -25.2122071, -57.5302746, true, 'Luque', 'minorista/gastronómico', 'NINGUNO');
INSERT INTO clientes (nombre, latitud, longitud, activo, ciudad, tipo_cliente, cadena) VALUES ('Aida Lopez', -25.3697471, -57.5271753, true, 'Asunción', 'minorista/gastronómico', 'NINGUNO');
INSERT INTO clientes (nombre, latitud, longitud, activo, ciudad, tipo_cliente, cadena) VALUES ('Twin SA', -25.2974825, -57.606024, true, 'Asunción', 'minorista/gastronómico', 'NINGUNO');
INSERT INTO clientes (nombre, latitud, longitud, activo, ciudad, tipo_cliente, cadena) VALUES ('Alberto Ibarra', -25.2826883, -57.5446192, true, 'Asunción', 'minorista/gastronómico', 'NINGUNO');
INSERT INTO clientes (nombre, latitud, longitud, activo, ciudad, tipo_cliente, cadena) VALUES ('Satori Zen Club Office', -25.2823483, -57.5452778, true, 'Asunción', 'minorista/gastronómico', 'NINGUNO');
INSERT INTO clientes (nombre, latitud, longitud, activo, ciudad, tipo_cliente, cadena) VALUES ('Pireka SA', -25.2784786, -57.581378, true, 'Asunción', 'minorista/gastronómico', 'NINGUNO');
INSERT INTO clientes (nombre, latitud, longitud, activo, ciudad, tipo_cliente, cadena) VALUES ('Paniz Vitae', -25.2709526, -57.5706442, true, 'Asunción', 'minorista/gastronómico', 'NINGUNO');
INSERT INTO clientes (nombre, latitud, longitud, activo, ciudad, tipo_cliente, cadena) VALUES ('Guadalupe hunicken', -25.2957295, -57.5841202, true, 'Asunción', 'minorista/gastronómico', 'NINGUNO');
INSERT INTO clientes (nombre, latitud, longitud, activo, ciudad, tipo_cliente, cadena) VALUES ('Esisa', -25.2996424, -57.5781453, true, 'Asunción', 'minorista/gastronómico', 'NINGUNO');
INSERT INTO clientes (nombre, latitud, longitud, activo, ciudad, tipo_cliente, cadena) VALUES ('Mara Guffanti Pasticcería', -25.3502979, -57.6038565, true, 'Asunción', 'minorista/gastronómico', 'NINGUNO');
INSERT INTO clientes (nombre, latitud, longitud, activo, ciudad, tipo_cliente, cadena) VALUES ('Elisandro Lopez', -25.3775518, -57.4732905, true, 'San Lorenzo', 'minorista/gastronómico', 'NINGUNO');
INSERT INTO clientes (nombre, latitud, longitud, activo, ciudad, tipo_cliente, cadena) VALUES ('La Quesería', -25.2839394, -57.6135167, true, 'Asunción', 'minorista/gastronómico', 'NINGUNO');
INSERT INTO clientes (nombre, latitud, longitud, activo, ciudad, tipo_cliente, cadena) VALUES ('lo Nuestro', -25.2855078, -57.5775231, true, 'Asunción', 'minorista/gastronómico', 'NINGUNO');
INSERT INTO clientes (nombre, latitud, longitud, activo, ciudad, tipo_cliente, cadena) VALUES ('Punto Carne Comercial', -25.3938206, -57.4851367, true, 'Capiatá', 'minorista/gastronómico', 'NINGUNO');
INSERT INTO clientes (nombre, latitud, longitud, activo, ciudad, tipo_cliente, cadena) VALUES ('Don Mario ', -25.3173884, -57.6074771, true, 'Asunción', 'minorista/gastronómico', 'NINGUNO');
INSERT INTO clientes (nombre, latitud, longitud, activo, ciudad, tipo_cliente, cadena) VALUES ('Nico Correa', -25.2928043, -57.5779872, true, 'Asunción', 'minorista/gastronómico', 'NINGUNO');
INSERT INTO clientes (nombre, latitud, longitud, activo, ciudad, tipo_cliente, cadena) VALUES ('Sibol', -25.282218, -57.6361898, true, 'Asunción', 'minorista/gastronómico', 'NINGUNO');
INSERT INTO clientes (nombre, latitud, longitud, activo, ciudad, tipo_cliente, cadena) VALUES ('Ara Poa', -25.2937501, -57.6435279, true, 'Asunción', 'minorista/gastronómico', 'NINGUNO');
INSERT INTO clientes (nombre, latitud, longitud, activo, ciudad, tipo_cliente, cadena) VALUES ('Hotel Villa Morra Suites', -25.2913505, -57.5856626, true, 'Asunción', 'minorista/gastronómico', 'NINGUNO');
INSERT INTO clientes (nombre, latitud, longitud, activo, ciudad, tipo_cliente, cadena) VALUES ('Pizza Kua', -25.3311288, -57.6110735, true, 'Asunción', 'minorista/gastronómico', 'NINGUNO');
INSERT INTO clientes (nombre, latitud, longitud, activo, ciudad, tipo_cliente, cadena) VALUES ('Flavio', -25.1652362, -57.5523604, true, 'Luque', 'minorista/gastronómico', 'NINGUNO');
INSERT INTO clientes (nombre, latitud, longitud, activo, ciudad, tipo_cliente, cadena) VALUES ('Alpha projects', -25.2859783, -57.5767902, true, 'Asunción', 'minorista/gastronómico', 'NINGUNO');
INSERT INTO clientes (nombre, latitud, longitud, activo, ciudad, tipo_cliente, cadena) VALUES ('7 Joyas', -25.2856053, -57.6201546, true, 'Asunción', 'minorista/gastronómico', 'NINGUNO');
INSERT INTO clientes (nombre, latitud, longitud, activo, ciudad, tipo_cliente, cadena) VALUES ('Almacen del Plata', -25.2890753, -57.5771664, true, 'Asunción', 'minorista/gastronómico', 'NINGUNO');
INSERT INTO clientes (nombre, latitud, longitud, activo, ciudad, tipo_cliente, cadena) VALUES ('Matias Villalba', -25.2756917, -57.5120872, true, 'Asunción', 'minorista/gastronómico', 'NINGUNO');
INSERT INTO clientes (nombre, latitud, longitud, activo, ciudad, tipo_cliente, cadena) VALUES ('Ivo Ortellado', -25.3252768, -57.5434172, true, 'Fernando de la Mora', 'minorista/gastronómico', 'NINGUNO');
INSERT INTO clientes (nombre, latitud, longitud, activo, ciudad, tipo_cliente, cadena) VALUES ('Patricia Ovelar', -25.4245709, -57.5036354, true, 'Ñemby', 'minorista/gastronómico', 'NINGUNO');
INSERT INTO clientes (nombre, latitud, longitud, activo, ciudad, tipo_cliente, cadena) VALUES ('Pollpar', -25.2680189, -57.5656363, true, 'Asunción', 'minorista/gastronómico', 'NINGUNO');
INSERT INTO clientes (nombre, latitud, longitud, activo, ciudad, tipo_cliente, cadena) VALUES ('Mantra', -25.2741188, -57.5666364, true, 'Asunción', 'minorista/gastronómico', 'NINGUNO');
INSERT INTO clientes (nombre, latitud, longitud, activo, ciudad, tipo_cliente, cadena) VALUES ('Emporio Alemán', -25.2898552, -57.5800875, true, 'Asunción', 'minorista/gastronómico', 'NINGUNO');
INSERT INTO clientes (nombre, latitud, longitud, activo, ciudad, tipo_cliente, cadena) VALUES ('Bizpar', -25.2704372, -57.5640461, true, 'Asunción', 'minorista/gastronómico', 'NINGUNO');
INSERT INTO clientes (nombre, latitud, longitud, activo, ciudad, tipo_cliente, cadena) VALUES ('Ycua', -25.2915162, -57.5849576, true, 'Asunción', 'minorista/gastronómico', 'NINGUNO');
INSERT INTO clientes (nombre, latitud, longitud, activo, ciudad, tipo_cliente, cadena) VALUES ('La Negrita Yakare Valija', -25.3412259, -57.5906686, true, 'Asunción', 'minorista/gastronómico', 'NINGUNO');
INSERT INTO clientes (nombre, latitud, longitud, activo, ciudad, tipo_cliente, cadena) VALUES ('Victor Molinas', -25.3917573, -57.5322217, true, 'Ñemby', 'minorista/gastronómico', 'NINGUNO');
INSERT INTO clientes (nombre, latitud, longitud, activo, ciudad, tipo_cliente, cadena) VALUES ('ESSENIA SACI', -25.3521933, -57.5725088, true, 'Asunción', 'minorista/gastronómico', 'NINGUNO');
INSERT INTO clientes (nombre, latitud, longitud, activo, ciudad, tipo_cliente, cadena) VALUES ('Sheraton Asuncion Hotel', -25.2839672, -57.5646901, true, 'Asunción', 'minorista/gastronómico', 'NINGUNO');
INSERT INTO clientes (nombre, latitud, longitud, activo, ciudad, tipo_cliente, cadena) VALUES ('Paramanta Lifestyle Hotel', -25.2782387, -57.5543797, true, 'Asunción', 'minorista/gastronómico', 'NINGUNO');
INSERT INTO clientes (nombre, latitud, longitud, activo, ciudad, tipo_cliente, cadena) VALUES ('El Cacique  Luque', -25.2716631, -57.4893186, true, 'Luque', 'minorista/gastronómico', 'NINGUNO');
INSERT INTO clientes (nombre, latitud, longitud, activo, ciudad, tipo_cliente, cadena) VALUES ('Cacique Itaugua', -25.3910787, -57.3553199, true, 'Itauguá', 'minorista/gastronómico', 'NINGUNO');
INSERT INTO clientes (nombre, latitud, longitud, activo, ciudad, tipo_cliente, cadena) VALUES ('Smart Foods', -25.2852138, -57.5611084, true, 'Asunción', 'minorista/gastronómico', 'NINGUNO');
INSERT INTO clientes (nombre, latitud, longitud, activo, ciudad, tipo_cliente, cadena) VALUES ('Bicolor', -25.2847969, -57.5682124, true, 'Asunción', 'minorista/gastronómico', 'NINGUNO');
INSERT INTO clientes (nombre, latitud, longitud, activo, ciudad, tipo_cliente, cadena) VALUES ('SUPERMAS ÑEMBY', -25.3696989, -57.5596926, true, 'Ñemby', 'supermercado', 'SUPERMAS');
INSERT INTO clientes (nombre, latitud, longitud, activo, ciudad, tipo_cliente, cadena) VALUES ('SUPERMAS S.A. abasto', -25.3253995, -57.5713844, true, 'Asunción', 'supermercado', 'SUPERMAS');
INSERT INTO clientes (nombre, latitud, longitud, activo, ciudad, tipo_cliente, cadena) VALUES ('delgado delvalle', -25.2856255, -57.6116716, true, 'Asunción', 'minorista/gastronómico', 'NINGUNO');
INSERT INTO clientes (nombre, latitud, longitud, activo, ciudad, tipo_cliente, cadena) VALUES ('Comercial La Arroyense', -25.3604118, -57.5255362, true, 'Asunción', 'minorista/gastronómico', 'NINGUNO');
INSERT INTO clientes (nombre, latitud, longitud, activo, ciudad, tipo_cliente, cadena) VALUES ('PRYCA Supermercado', -25.3304532, -57.5930484, true, 'Asunción', 'supermercado', 'PRYCA');
INSERT INTO clientes (nombre, latitud, longitud, activo, ciudad, tipo_cliente, cadena) VALUES ('Belcorp', -25.2695525, -57.4961271, true, 'Luque', 'minorista/gastronómico', 'NINGUNO');
INSERT INTO clientes (nombre, latitud, longitud, activo, ciudad, tipo_cliente, cadena) VALUES ('Fatima Da Silva', -25.3640129, -57.5771867, true, 'Asunción', 'minorista/gastronómico', 'NINGUNO');
INSERT INTO clientes (nombre, latitud, longitud, activo, ciudad, tipo_cliente, cadena) VALUES ('Gran Vía luque', -25.2805841, -57.5258219, true, 'Luque', 'supermercado', 'GRAN VIA');
INSERT INTO clientes (nombre, latitud, longitud, activo, ciudad, tipo_cliente, cadena) VALUES ('Gran Via Supermarket ñemby', -25.3954616, -57.5454823, true, 'Ñemby', 'supermercado', 'GRAN VIA');
INSERT INTO clientes (nombre, latitud, longitud, activo, ciudad, tipo_cliente, cadena) VALUES ('Gran via Royal Plaza', -25.3082675, -57.5525855, true, 'Asunción', 'supermercado', 'GRAN VIA');
INSERT INTO clientes (nombre, latitud, longitud, activo, ciudad, tipo_cliente, cadena) VALUES ('Gran Via Supermarket', -25.3954616, -57.5454823, true, 'Ñemby', 'supermercado', 'GRAN VIA');
INSERT INTO clientes (nombre, latitud, longitud, activo, ciudad, tipo_cliente, cadena) VALUES ('Supermarket Gran Vía asucion', -25.3081601, -57.5967149, true, 'Asunción', 'supermercado', 'GRAN VIA');
INSERT INTO clientes (nombre, latitud, longitud, activo, ciudad, tipo_cliente, cadena) VALUES ('Salemma Multiplaza', -25.316031, -57.5697833, true, 'Asunción', 'supermercado', 'SALEMMA');
INSERT INTO clientes (nombre, latitud, longitud, activo, ciudad, tipo_cliente, cadena) VALUES ('Salemma Carmelitas', -25.2847494, -57.5724531, true, 'Asunción', 'supermercado', 'SALEMMA');
INSERT INTO clientes (nombre, latitud, longitud, activo, ciudad, tipo_cliente, cadena) VALUES ('Fuente Shopping', -25.3345529, -57.5371466, true, 'Asunción', 'supermercado', 'SALEMMA');
INSERT INTO clientes (nombre, latitud, longitud, activo, ciudad, tipo_cliente, cadena) VALUES ('Salemma - San Lorenzo', -25.3420804, -57.4885308, true, 'San Lorenzo', 'supermercado', 'SALEMMA');
INSERT INTO clientes (nombre, latitud, longitud, activo, ciudad, tipo_cliente, cadena) VALUES ('Casa Rica España', -25.2855573, -57.5862293, true, 'Asunción', 'supermercado', 'CASA RICA');
INSERT INTO clientes (nombre, latitud, longitud, activo, ciudad, tipo_cliente, cadena) VALUES ('Casa Rica - Molas López', -25.2722849, -57.5714394, true, 'Asunción', 'supermercado', 'CASA RICA');
INSERT INTO clientes (nombre, latitud, longitud, activo, ciudad, tipo_cliente, cadena) VALUES ('Areté Primer Presidente', -25.2593937, -57.5664943, true, 'Asunción', 'supermercado', 'ARETÉ');
INSERT INTO clientes (nombre, latitud, longitud, activo, ciudad, tipo_cliente, cadena) VALUES ('Casa Rica Los Laureles', -25.3082903, -57.5766411, true, 'Asunción', 'supermercado', 'CASA RICA');
INSERT INTO clientes (nombre, latitud, longitud, activo, ciudad, tipo_cliente, cadena) VALUES ('Areté Lambare', -25.3422195, -57.6073503, true, 'Lambaré', 'supermercado', 'ARETÉ');
INSERT INTO clientes (nombre, latitud, longitud, activo, ciudad, tipo_cliente, cadena) VALUES ('Areté Sausalito', -25.2674118, -57.5934885, true, 'Asunción', 'supermercado', 'ARETÉ');
INSERT INTO clientes (nombre, latitud, longitud, activo, ciudad, tipo_cliente, cadena) VALUES ('El Ahorrazo San Lorenzo', -25.3442505, -57.5104264, true, 'San Lorenzo', 'supermercado', 'EL AHORRAZO');
INSERT INTO clientes (nombre, latitud, longitud, activo, ciudad, tipo_cliente, cadena) VALUES ('EL AHORRAZO - SUC CAPIATA', -25.392956, -57.4698581, true, 'Capiatá', 'supermercado', 'EL AHORRAZO');
INSERT INTO clientes (nombre, latitud, longitud, activo, ciudad, tipo_cliente, cadena) VALUES ('Superseis - Portal', -25.2387517, -57.5422655, true, 'Luque', 'supermercado', 'SUPERSEIS');
INSERT INTO clientes (nombre, latitud, longitud, activo, ciudad, tipo_cliente, cadena) VALUES ('Superseis - Fernando de la mora', -25.3156903, -57.5275784, true, 'Fernando de la Mora', 'supermercado', 'SUPERSEIS');
INSERT INTO clientes (nombre, latitud, longitud, activo, ciudad, tipo_cliente, cadena) VALUES ('Hiperseis hypermarket', -25.3027058, -57.5642771, true, 'Asunción', 'supermercado', 'SUPERSEIS');
INSERT INTO clientes (nombre, latitud, longitud, activo, ciudad, tipo_cliente, cadena) VALUES ('Superseis San Lorenzo', -25.3428897, -57.5018865, true, 'San Lorenzo', 'supermercado', 'SUPERSEIS');
INSERT INTO clientes (nombre, latitud, longitud, activo, ciudad, tipo_cliente, cadena) VALUES ('Superseis lambare', -25.3411121, -57.5994644, true, 'Lambaré', 'supermercado', 'SUPERSEIS');
INSERT INTO clientes (nombre, latitud, longitud, activo, ciudad, tipo_cliente, cadena) VALUES ('Superseis - Mburucuya', -25.2702565, -57.5629748, true, 'Asunción', 'supermercado', 'SUPERSEIS');
INSERT INTO clientes (nombre, latitud, longitud, activo, ciudad, tipo_cliente, cadena) VALUES ('Superseis - laureles', -25.3050444, -57.5832982, true, 'Asunción', 'supermercado', 'SUPERSEIS');
INSERT INTO clientes (nombre, latitud, longitud, activo, ciudad, tipo_cliente, cadena) VALUES ('Superseis - total', -25.288242, -57.6490563, true, 'Asunción', 'supermercado', 'SUPERSEIS');
INSERT INTO clientes (nombre, latitud, longitud, activo, ciudad, tipo_cliente, cadena) VALUES ('Superseis - Mundi Mark', -25.2874104, -57.6058491, true, 'Asunción', 'supermercado', 'SUPERSEIS');
INSERT INTO clientes (nombre, latitud, longitud, activo, ciudad, tipo_cliente, cadena) VALUES ('Superseis - la negrita', -25.3013658, -57.6174629, true, 'Asunción', 'supermercado', 'SUPERSEIS');
INSERT INTO clientes (nombre, latitud, longitud, activo, ciudad, tipo_cliente, cadena) VALUES ('Superseis Gran Unión', -25.2894812, -57.590135, true, 'Asunción', 'supermercado', 'SUPERSEIS');
INSERT INTO clientes (nombre, latitud, longitud, activo, ciudad, tipo_cliente, cadena) VALUES ('Superseis - Denis Roa', -25.2922607, -57.5596865, true, 'Asunción', 'supermercado', 'SUPERSEIS');
INSERT INTO clientes (nombre, latitud, longitud, activo, ciudad, tipo_cliente, cadena) VALUES ('Superseis Aregua', -25.311195, -57.3797662, true, 'Areguá', 'supermercado', 'SUPERSEIS');
INSERT INTO clientes (nombre, latitud, longitud, activo, ciudad, tipo_cliente, cadena) VALUES ('Superseis luque', -25.2625244, -57.4899483, true, 'Luque', 'supermercado', 'SUPERSEIS');
INSERT INTO clientes (nombre, latitud, longitud, activo, ciudad, tipo_cliente, cadena) VALUES ('Superseis - Paseo La Galería', -25.2847299, -57.5635388, true, 'Asunción', 'supermercado', 'SUPERSEIS');
INSERT INTO clientes (nombre, latitud, longitud, activo, ciudad, tipo_cliente, cadena) VALUES ('Superseis Kamba Kuá', -25.3213096, -57.5244312, true, 'Fernando de la Mora', 'supermercado', 'SUPERSEIS');
INSERT INTO clientes (nombre, latitud, longitud, activo, ciudad, tipo_cliente, cadena) VALUES ('Superseis Villeta', -25.5083923, -57.5590476, true, 'Villeta', 'supermercado', 'SUPERSEIS');
INSERT INTO clientes (nombre, latitud, longitud, activo, ciudad, tipo_cliente, cadena) VALUES ('Superseis Villamorra', -25.2940035, -57.5821533, true, 'Asunción', 'supermercado', 'SUPERSEIS');
INSERT INTO clientes (nombre, latitud, longitud, activo, ciudad, tipo_cliente, cadena) VALUES ('Superseis San Bernardino', -25.3050246, -57.2957826, true, 'San Bernardino', 'supermercado', 'SUPERSEIS');
INSERT INTO clientes (nombre, latitud, longitud, activo, ciudad, tipo_cliente, cadena) VALUES ('Superseis Ñemby', -25.3934509, -57.5440193, true, 'Ñemby', 'supermercado', 'SUPERSEIS');
INSERT INTO clientes (nombre, latitud, longitud, activo, ciudad, tipo_cliente, cadena) VALUES ('Superseis Laurelty', -25.2895062, -57.5003427, true, 'Luque', 'supermercado', 'SUPERSEIS');
INSERT INTO clientes (nombre, latitud, longitud, activo, ciudad, tipo_cliente, cadena) VALUES ('Superseis - España', -25.285771, -57.6208623, true, 'Asunción', 'supermercado', 'SUPERSEIS');
INSERT INTO clientes (nombre, latitud, longitud, activo, ciudad, tipo_cliente, cadena) VALUES ('Superseis Japón', -25.3185226, -57.6298757, true, 'Asunción', 'supermercado', 'SUPERSEIS');
INSERT INTO clientes (nombre, latitud, longitud, activo, ciudad, tipo_cliente, cadena) VALUES ('Super Seis  Madero', -25.2554613, -57.5124199, true, 'Luque', 'supermercado', 'SUPERSEIS');
INSERT INTO clientes (nombre, latitud, longitud, activo, ciudad, tipo_cliente, cadena) VALUES ('Superseis Sirio', -25.3345913, -57.6249111, true, 'Asunción', 'supermercado', 'SUPERSEIS');
INSERT INTO clientes (nombre, latitud, longitud, activo, ciudad, tipo_cliente, cadena) VALUES ('Superseis Caacupé', -25.3893223, -57.1508141, true, 'Caacupé', 'supermercado', 'SUPERSEIS');
INSERT INTO clientes (nombre, latitud, longitud, activo, ciudad, tipo_cliente, cadena) VALUES ('Bahia Autopista', -25.2825998, -57.562527, true, 'Asunción', 'minorista/gastronómico', 'NINGUNO');
INSERT INTO clientes (nombre, latitud, longitud, activo, ciudad, tipo_cliente, cadena) VALUES ('bahia Sacramento', -25.2672176, -57.5826744, true, 'Asunción', 'minorista/gastronómico', 'NINGUNO');
INSERT INTO clientes (nombre, latitud, longitud, activo, ciudad, tipo_cliente, cadena) VALUES ('Bahia Aeropuerto', -25.231947, -57.538318, true, 'Luque', 'minorista/gastronómico', 'NINGUNO');
INSERT INTO clientes (nombre, latitud, longitud, activo, ciudad, tipo_cliente, cadena) VALUES ('Bahía Cacique', -25.3426752, -57.6059663, true, 'Lambaré', 'minorista/gastronómico', 'NINGUNO');
INSERT INTO clientes (nombre, latitud, longitud, activo, ciudad, tipo_cliente, cadena) VALUES ('Bahia San Nicolas', -25.334594, -57.5344103, true, 'Asunción', 'minorista/gastronómico', 'NINGUNO');
INSERT INTO clientes (nombre, latitud, longitud, activo, ciudad, tipo_cliente, cadena) VALUES ('Bahia Yvera', -25.3366423, -57.510741, true, 'Asunción', 'minorista/gastronómico', 'NINGUNO');
INSERT INTO clientes (nombre, latitud, longitud, activo, ciudad, tipo_cliente, cadena) VALUES ('Bahía  Aviadores', -25.286511, -57.571293, true, 'Asunción', 'minorista/gastronómico', 'NINGUNO');
INSERT INTO clientes (nombre, latitud, longitud, activo, ciudad, tipo_cliente, cadena) VALUES ('Bahia Botanico', -25.2522661, -57.5789476, true, 'Asunción', 'minorista/gastronómico', 'NINGUNO');
INSERT INTO clientes (nombre, latitud, longitud, activo, ciudad, tipo_cliente, cadena) VALUES ('Bahia  Centro', -25.278923, -57.6387698, true, 'Asunción', 'minorista/gastronómico', 'NINGUNO');
INSERT INTO clientes (nombre, latitud, longitud, activo, ciudad, tipo_cliente, cadena) VALUES ('Bahia Acceso 2', -25.345836, -57.5782476, true, 'Asunción', 'minorista/gastronómico', 'NINGUNO');
INSERT INTO clientes (nombre, latitud, longitud, activo, ciudad, tipo_cliente, cadena) VALUES ('Bahia  Surubi i', -25.1920676, -57.5058703, true, 'Luque', 'minorista/gastronómico', 'NINGUNO');
INSERT INTO clientes (nombre, latitud, longitud, activo, ciudad, tipo_cliente, cadena) VALUES ('Shell Mcal2', -25.3107025, -57.5306586, true, 'Fernando de la Mora', 'minorista/gastronómico', 'NINGUNO');
INSERT INTO clientes (nombre, latitud, longitud, activo, ciudad, tipo_cliente, cadena) VALUES ('bahia itaugua', -25.3779739, -57.4010854, true, 'Itauguá', 'minorista/gastronómico', 'NINGUNO');
INSERT INTO clientes (nombre, latitud, longitud, activo, ciudad, tipo_cliente, cadena) VALUES ('Real supermarket Capiatá 2', -25.3502433, -57.4477089, true, 'Capiatá', 'supermercado', 'REAL');
INSERT INTO clientes (nombre, latitud, longitud, activo, ciudad, tipo_cliente, cadena) VALUES ('Supermercado Real Capiatá 1', -25.3652226, -57.481201, true, 'Capiatá', 'supermercado', 'REAL');
INSERT INTO clientes (nombre, latitud, longitud, activo, ciudad, tipo_cliente, cadena) VALUES ('Real Supermarket ñemby 2', -25.3944556, -57.542697, true, 'Ñemby', 'supermercado', 'REAL');
INSERT INTO clientes (nombre, latitud, longitud, activo, ciudad, tipo_cliente, cadena) VALUES ('Supermarket Real Fernando', -25.3278468, -57.5474224, true, 'Fernando de la Mora', 'supermercado', 'REAL');
INSERT INTO clientes (nombre, latitud, longitud, activo, ciudad, tipo_cliente, cadena) VALUES ('Real San Vicente supermarket', -25.3087363, -57.6175591, true, 'Asunción', 'supermercado', 'REAL');
INSERT INTO clientes (nombre, latitud, longitud, activo, ciudad, tipo_cliente, cadena) VALUES ('Real Félix Bogado', -25.3239925, -57.6273226, true, 'Asunción', 'supermercado', 'REAL');
INSERT INTO clientes (nombre, latitud, longitud, activo, ciudad, tipo_cliente, cadena) VALUES ('Supermarket Real acceso sur', -25.3466961, -57.574971, true, 'Asunción', 'supermercado', 'REAL');
INSERT INTO clientes (nombre, latitud, longitud, activo, ciudad, tipo_cliente, cadena) VALUES ('Real villamorra', -25.2971693, -57.5788706, true, 'Asunción', 'supermercado', 'REAL');
INSERT INTO clientes (nombre, latitud, longitud, activo, ciudad, tipo_cliente, cadena) VALUES ('Real Supermarket ñemby1', -25.3934203, -57.5473369, true, 'Ñemby', 'supermercado', 'REAL');
INSERT INTO clientes (nombre, latitud, longitud, activo, ciudad, tipo_cliente, cadena) VALUES ('Encina', -25.3267272, -57.5723867, true, 'Asunción', 'distribuidor/mayorista', 'ENCINA');
INSERT INTO clientes (nombre, latitud, longitud, activo, ciudad, tipo_cliente, cadena) VALUES ('Fraxa', -25.3564554, -57.4900121, true, 'San Lorenzo', 'distribuidor/mayorista', 'FRAXA');
INSERT INTO clientes (nombre, latitud, longitud, activo, ciudad, tipo_cliente, cadena) VALUES ('Kiko Productos de Confianza', -25.3250033, -57.5717947, true, 'Asunción', 'distribuidor/mayorista', 'KIKO');
INSERT INTO clientes (nombre, latitud, longitud, activo, ciudad, tipo_cliente, cadena) VALUES ('Bellini Palma', -25.2813655, -57.6364167, true, 'Asunción', 'minorista/gastronómico', 'NINGUNO');
INSERT INTO clientes (nombre, latitud, longitud, activo, ciudad, tipo_cliente, cadena) VALUES ('Bellini Carmelitas', -25.2858541, -57.5774822, true, 'Asunción', 'minorista/gastronómico', 'NINGUNO');
INSERT INTO clientes (nombre, latitud, longitud, activo, ciudad, tipo_cliente, cadena) VALUES ('Bellini Pasta Multiplaza.', -25.3167296, -57.5720783, true, 'Asunción', 'minorista/gastronómico', 'NINGUNO');
INSERT INTO clientes (nombre, latitud, longitud, activo, ciudad, tipo_cliente, cadena) VALUES ('Bellini Sajonia', -25.2887625, -57.6531071, true, 'Asunción', 'minorista/gastronómico', 'NINGUNO');
INSERT INTO clientes (nombre, latitud, longitud, activo, ciudad, tipo_cliente, cadena) VALUES ('Bellini Sol', -25.2828559, -57.5666743, true, 'Asunción', 'minorista/gastronómico', 'NINGUNO');
INSERT INTO clientes (nombre, latitud, longitud, activo, ciudad, tipo_cliente, cadena) VALUES ('Bellini - Paseo La Galeria', -25.2847299, -57.5635388, true, 'Asunción', 'minorista/gastronómico', 'NINGUNO');
INSERT INTO clientes (nombre, latitud, longitud, activo, ciudad, tipo_cliente, cadena) VALUES ('Bellini - Pinedo', -25.3231204, -57.5195926, true, 'Fernando de la Mora', 'minorista/gastronómico', 'NINGUNO');
INSERT INTO clientes (nombre, latitud, longitud, activo, ciudad, tipo_cliente, cadena) VALUES ('Bellini Shopping Mariscal', -25.2948434, -57.5821394, true, 'Asunción', 'minorista/gastronómico', 'NINGUNO');
INSERT INTO clientes (nombre, latitud, longitud, activo, ciudad, tipo_cliente, cadena) VALUES ('Bellini il mercato', -25.29487, -57.581982, true, 'Asunción', 'minorista/gastronómico', 'NINGUNO');
INSERT INTO clientes (nombre, latitud, longitud, activo, ciudad, tipo_cliente, cadena) VALUES ('Bellini San Lorenzo', -25.342317, -57.4878443, true, 'San Lorenzo', 'minorista/gastronómico', 'NINGUNO');
INSERT INTO clientes (nombre, latitud, longitud, activo, ciudad, tipo_cliente, cadena) VALUES ('Bellini Mariano', -25.2257216, -57.5368055, true, 'Mariano Roque Alonso', 'minorista/gastronómico', 'NINGUNO');
INSERT INTO clientes (nombre, latitud, longitud, activo, ciudad, tipo_cliente, cadena) VALUES ('Bellini Los Jardines', -25.2651443, -57.5074139, true, 'Luque', 'minorista/gastronómico', 'NINGUNO');
INSERT INTO clientes (nombre, latitud, longitud, activo, ciudad, tipo_cliente, cadena) VALUES ('Bellini Fuente Shopping', -25.3348688, -57.5368826, true, 'Asunción', 'minorista/gastronómico', 'NINGUNO');
INSERT INTO clientes (nombre, latitud, longitud, activo, ciudad, tipo_cliente, cadena) VALUES ('BOX Mayorista - Aratiri', -25.3463861, -57.4781637, true, 'San Lorenzo', 'supermercado', 'BOX');
INSERT INTO clientes (nombre, latitud, longitud, activo, ciudad, tipo_cliente, cadena) VALUES ('BOX Mayorista Manuel Ortiz Guerrero', -25.3674232, -57.5165948, true, 'Asunción', 'supermercado', 'BOX');
INSERT INTO clientes (nombre, latitud, longitud, activo, ciudad, tipo_cliente, cadena) VALUES ('BOX MAYORISTA r1', -25.3846168, -57.4704475, true, 'Capiatá', 'supermercado', 'BOX');
INSERT INTO clientes (nombre, latitud, longitud, activo, ciudad, tipo_cliente, cadena) VALUES ('BOX SUPERMAYORISTA ABASTO', -25.3249021, -57.5720697, true, 'Asunción', 'supermercado', 'BOX');
INSERT INTO clientes (nombre, latitud, longitud, activo, ciudad, tipo_cliente, cadena) VALUES ('Box Luque', -25.2755997, -57.4855999, true, 'Luque', 'supermercado', 'BOX');